### ISSUE TITLE
Monet Theming Engine Regresion

### ISSUE THREAD

**Issue by KoremuMekuro** [crdroidandroid/crdroid_features#86]
With 9.3, firstly on redmi note 8t and then on poco f3 with second 9.3 update I noticed that with this changed theming options I can't have anymore vibrant colors.Only with proprietary repainter I can achive vibrant colors.Why that was changed?Is there any hope that old theming option will be returned?Or maybe there will be added options, so it will be possible to achive vibrant colors?
![Screenshot_20230407-183140_Налаштування](https://user-images.githubusercontent.com/125179297/230636963-83321b4b-6449-4af6-be60-c22da3dc17d3.png)
![Screenshot_20230407-183152_crDroid Home](https://user-images.githubusercontent.com/125179297/230636968-93ab3f6e-0670-44be-8c70-7ed0482bd580.png)
![Screenshot_20230407-183212_crDroid Home](https://user-images.githubusercontent.com/125179297/230636970-142e56c7-2dc2-47b7-861a-839ac29d6187.png)
![Screenshot_20230407-183821_Налаштування](https://user-images.githubusercontent.com/125179297/230637024-4918d755-7c1e-47de-aa34-85915d411021.png)
![Screenshot_20230407-183814_Налаштування](https://user-images.githubusercontent.com/125179297/230637030-1007f7cb-693e-419d-a317-c8c2d97d0553.png)
![Screenshot_20230407-183800_Repainter](https://user-images.githubusercontent.com/125179297/230637031-f70563e8-0d46-474d-8f2b-ab9d668d212f.png)

**Comment by neobuddy89** [comment]
This was fixed recently. 
https://github.com/crdroidandroid/android_frameworks_base/commit/04ffb02a43ec7b86ace2dc9ca18dfc8bf51e4edf
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/527c54c64ee3f00b45fc029d14baf55b8cb83924

**Comment by KoremuMekuro** [comment]
> This was fixed recently. [crdroidandroid/android_frameworks_base@04ffb02](https://github.com/crdroidandroid/android_frameworks_base/commit/04ffb02a43ec7b86ace2dc9ca18dfc8bf51e4edf) [crdroidandroid/android_packages_apps_crDroidSettings@527c54c](https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/527c54c64ee3f00b45fc029d14baf55b8cb83924)

This wasn't fixed.On poco f3 update was only a day ago.And in the commit there are still the same options from this 9.3 update and not from march 31st 9.3 or 9.2 and earlier.

**Comment by neobuddy89** [comment]
@KoremuMekuro what is issue on poco f3 you facing

**Comment by KoremuMekuro** [comment]
> @KoremuMekuro what is issue on poco f3 you facing

Issue is the 'new' monet theming options.This 'new' options are producing bad results as opposed to march 31st 9.3 build and erlier, on which there was older monet theming options that dosen't have such problem.Described and showcased it all above.Or maybe I need to do all screenshots again with english language and then downgrade to march 31st build of 9.3 and show older(better) monet theming options?
crdroidandroid/android_frameworks_base@04ffb02
crdroidandroid/android_packages_apps_crDroidSettings@527c54c
This commits are what caused my issue.
